# General
install_ansible_modules: "true"
disable_transparent_huge_pages: "true"
setup_interface: "false"

#SSH
ssh_port: 2222

# DNS
resolv_nameservers: [178.22.122.100, 185.51.200.2]

# Sanction
use_iran: "true" # change it to "false" if you are outside of iran :)

DNS1: 10.202.10.202
DNS2: 10.202.10.102