---
# tasks file for sentinel
- name: find master private ip
  set_fact:
    master_ip: "{{ hostvars[item].private_ip }}"
  when: "'role' in hostvars[item] and hostvars[item].role == 'master'"
  loop: "{{ groups['all'] }}"

- name: show master ip
  debug:
    msg: "{{ master_ip }}"

- name: Configure sentinel
  lineinfile:
    path: /etc/redis/sentinel.conf
    line: sentinel monitor mymaster {{ master_ip }} 6379 2
    create: yes

- name: set permission for user 'redis'
  file:
    path: /etc/redis/sentinel.conf
    owner: redis
    group: redis
    mode: '0644'

- name: Copy sentinel systemd file
  template:
    src: templates/sentinel.service.j2
    dest: /etc/systemd/system/redis-sentinel.service
    owner: root
    group: root
    mode: 0644

- name: Reload systemd daemon
  systemd_service:
    daemon_reload: true

- name: Start sentinel service
  systemd:
    name: redis-sentinel
    state: started
    enabled: yes